version: "3.7"
services:
  dashboard-dev:
    image: erasme/co2-dashboard:dev
    build:
      context: dashboard/
      target: "prod"
    volumes:
      - ./dashboard/src/:/app/src
      - ./dashboard/package.json:/app/package.json
      - ./dashboard/package-lock.json:/app/package-lock.json
    ports:
      - "5173:5173"
    env_file:
      - .env
